# Server settings
server:
    port: 8080
    address: localhost
    contextPath: /

#datasource
spring:
  datasource:
    primary:
      url: jdbc:mysql://120.25.205.4:3306/spring-boot-background?useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://120.25.205.4:3306/spring-boot-background-1?useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

#设置环境变量,决定读取那个环境的参数,打包后通过 java -jar xxx.jar --spring.profiles.active=test 来指定环境
  profiles:
    active: dev

#redis
  redis:
    host-name: 120.25.205.4
    port: 6379
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#自定义参数
cn:
  lzg:
    name: 郎志刚
    age: 25
    desc: name:${cn.lzg.name} age:${cn.lzg.age}

#日志
logging:
  config: classpath:logback-spring.xml
